// === emoji-data.js - Complete Fixed Version ===

window.EMOJI_MAPPING = {
    // SMILEYS & EMOTION
    '😀':'grinning_face','😃':'smiling_face_open_mouth','😄':'smiling_face_open_mouth_smiling_eyes','😁':'beaming_face_smiling_eyes','😅':'smiling_face_sweat','😂':'face_tears_joy','🤣':'rolling_on_floor_laughing','🙂':'slightly_smiling_face','🙃':'upside_down_face','😉':'winking_face','😊':'smiling_face_smiling_eyes','😇':'smiling_face_halo','🥰':'smiling_face_hearts','😍':'smiling_face_heart_eyes','🤩':'star_struck','😘':'face_blowing_kiss','😗':'kissing_face','☺️':'smiling_face','😚':'kissing_face_closed_eyes','😙':'kissing_face_smiling_eyes','😋':'face_savoring_food','😛':'face_tongue','😜':'winking_face_tongue','🤪':'zany_face','😝':'squinting_face_tongue','🤑':'money_mouth_face','🤗':'hugging_face','🤭':'face_hand_over_mouth','🤫':'shushing_face','🤔':'thinking_face','🤐':'zipper_mouth_face','🤨':'face_raised_eyebrow','😐':'neutral_face','😑':'expressionless_face','😶':'face_no_mouth','😏':'smirking_face','😒':'unamused_face','🙄':'face_with_rolling_eyes','😬':'grimacing_face','🤥':'lying_face','😌':'relieved_face','😔':'pensive_face','😪':'sleepy_face','🤤':'drooling_face','😴':'sleeping_face','😷':'face_medical_mask','🤒':'face_temperature','🤕':'face_bandage','🤢':'nauseated_face','🤮':'face_vomit','🤧':'sneezing_face','🥵':'hot_face','🥶':'cold_face','🥴':'woozy_face','😵':'dizzy_face','🤯':'exploding_head','🤠':'cowboy_hat_face','🥳':'partying_face','🥸':'disguised_face','😎':'smiling_face_sunglasses','🤓':'nerd_face','🧐':'face_monocle','😕':'confused_face','😟':'worried_face','🙁':'slightly_frowning_face','☹️':'frowning_face','😮':'face_open_mouth','😯':'hushed_face','😲':'astonished_face','😳':'flushed_face','🥺':'pleading_face','😦':'frowning_face_open_mouth','😧':'anguished_face','😨':'fearful_face','😰':'anxious_face_sweat','😥':'sad_but_relieved_face','😢':'crying_face','😭':'loudly_crying_face','😱':'face_screaming_fear','😖':'confounded_face','😣':'persevering_face','😞':'disappointed_face','😓':'downcast_face_sweat','😩':'weary_face','😫':'tired_face','🥱':'yawning_face','😤':'face_steaming_nose','😡':'enraged_face','😠':'angry_face','🤬':'face_symbols_mouth','😈':'smiling_face_horns','👿':'angry_face_horns','💀':'skull','☠️':'skull_crossbones','💩':'pile_poo','🤡':'clown_face','👹':'ogre','👺':'goblin','👻':'ghost','👽':'alien','👾':'alien_monster','🤖':'robot',
    
    // PEOPLE & BODY
    '👶':'baby','👧':'girl','🧒':'child','👦':'boy','👩':'woman','🧑':'person','👨':'man','👴':'old_man','👵':'old_woman','🧓':'older_person','👱':'person_blonde','👨‍⚕️':'man_health_worker','👩‍⚕️':'woman_health_worker','👨‍🎓':'man_student','👩‍🎓':'woman_student','👨‍🏫':'man_teacher','👩‍🏫':'woman_teacher','👨‍⚖️':'man_judge','👩‍⚖️':'woman_judge','👨‍🌾':'man_farmer','👩‍🌾':'woman_farmer','👨‍🍳':'man_cook','👩‍🍳':'woman_cook','👨‍🔧':'man_mechanic','👩‍🔧':'woman_mechanic','👨‍🏭':'man_factory_worker','👩‍🏭':'woman_factory_worker','👨‍💼':'man_office_worker','👩‍💼':'woman_office_worker','👨‍🔬':'man_scientist','👩‍🔬':'woman_scientist','👨‍💻':'man_technologist','👩‍💻':'woman_technologist','👨‍🎤':'man_singer','👩‍🎤':'woman_singer','👨‍🎨':'man_artist','👩‍🎨':'woman_artist','👨‍✈️':'man_pilot','👩‍✈️':'woman_pilot','👨‍🚀':'man_astronaut','👩‍🚀':'woman_astronaut','👨‍🚒':'man_firefighter','👩‍🚒':'woman_firefighter','👮':'police_officer','🕵️':'detective','💂':'guard','👷':'construction_worker','🤴':'prince','👸':'princess','👳':'person_turban','👲':'person_skullcap','🧕':'woman_headscarf','🤵':'person_tuxedo','👰':'person_veil','🤰':'pregnant_woman','🤱':'breastfeeding','👼':'baby_angel','🎅':'santa_claus','🤶':'mrs_claus','🦸':'superhero','🦹':'supervillain','🧙':'mage','🧚':'fairy','🧛':'vampire','🧜':'merperson','🧝':'elf','🧞':'genie','🧟':'zombie','💆':'person_massage','💇':'person_haircut','🚶':'person_walking','🏃':'person_running','💃':'woman_dancing','🕺':'man_dancing','🕴️':'person_suit_float','🧖':'person_steam_room','🧗':'person_climbing','🧘':'person_lotus_position','💪':'flexed_biceps','🦾':'mechanical_arm','🦿':'mechanical_leg','🦵':'leg','🦶':'foot','👂':'ear','🦻':'ear_hearing_aid','👃':'nose','🧠':'brain','🦷':'tooth','🦴':'bone','👀':'eyes','👁️':'eye','👅':'tongue','👄':'lips','🙌':'raising_hands','👐':'open_hands','🤲':'palms_up_together','🤝':'handshake','🙏':'folded_hands','✍️':'writing_hand',
    
    // ANIMALS
    '🐶':'dog','🐱':'cat','🐭':'mouse','🐹':'hamster','🐰':'rabbit','🦊':'fox','🐻':'bear','🐼':'panda','🐨':'koala','🐯':'tiger','🦁':'lion','🐮':'cow','🐷':'pig','🐸':'frog','🐵':'monkey','🙈':'see_no_evil_monkey','🙉':'hear_no_evil_monkey','🙊':'speak_no_evil_monkey','🐒':'monkey','🐔':'chicken','🐧':'penguin','🐦':'bird','🐤':'baby_chick','🐥':'front_facing_baby_chick','🐣':'hatching_chick','🦆':'duck','🦅':'eagle','🦉':'owl','🦇':'bat','🐺':'wolf','🐗':'boar','🐴':'horse','🦄':'unicorn','🐝':'bee','🐛':'bug','🦋':'butterfly','🐌':'snail','🐞':'lady_beetle','🐜':'ant','🦟':'mosquito','🦗':'cricket','🕷️':'spider','🦂':'scorpion','🐢':'turtle','🐍':'snake','🦎':'lizard','🐙':'octopus','🦑':'squid','🦐':'shrimp','🦀':'crab','🐡':'blowfish','🐠':'tropical_fish','🐟':'fish','🐬':'dolphin','🐳':'whale','🐋':'whale','🦈':'shark','🐊':'crocodile','🐅':'tiger','🐆':'leopard','🦓':'zebra','🦍':'gorilla','🦧':'orangutan','🐘':'elephant','🦏':'rhino','🦛':'hippopotamus','🐪':'camel','🐫':'two_hump_camel','🦒':'giraffe','🦘':'kangaroo','🐃':'water_buffalo','🐂':'ox','🐄':'cow','🐎':'horse','🐖':'pig','🐏':'ram','🐐':'goat','🐑':'sheep','🦙':'llama','🦝':'raccoon','🦡':'badger','🦦':'otter','🦨':'skunk','🐿️':'chipmunk','🦔':'hedgehog',
    
    // NATURE
    '🔥':'fire','💧':'droplet','🌊':'water_wave','🎃':'jack_o_lantern','✨':'sparkles','🎋':'tanabata_tree','🎍':'pine_decorations','🎀':'ribbon','🎁':'gift','🎈':'balloon','🎉':'party_popper','🎊':'confetti_ball','🍼':'baby_bottle','🥛':'glass_milk','☀️':'sun','🌝':'full_moon','🌞':'sun_face','🪐':'ringed_planet','⭐':'star','🌟':'glowing_star','🌙':'crescent_moon','🌚':'new_moon','🌛':'first_quarter_moon','🌜':'last_quarter_moon','🌑':'new_moon_symbol','🌒':'waxing_crescent_moon','🌓':'first_quarter_moon_symbol','🌔':'waxing_gibbous_moon','🌕':'full_moon_symbol','🌖':'waning_gibbous_moon','🌗':'last_quarter_moon_symbol','🌘':'waning_crescent_moon','🌡️':'thermometer','☁️':'cloud','⛅':'partly_sunny','⛈️':'thunder_cloud_rain','🌧️':'cloud_rain','🌨️':'cloud_snow','❄️':'snowflake','🌬️':'wind_blowing_face','🌪️':'tornado','🌫️':'fog','🌈':'rainbow','☂️':'umbrella','☔':'umbrella_raindrops','⚡':'zap','🍄':'mushroom','🌰':'chestnut','🌲':'evergreen_tree'
};

// Continue from Part A...

// ADD REMAINING MAPPINGS for food, travel, symbols, etc.
Object.assign(window.EMOJI_MAPPING, {
    // FOOD & DRINK
    '🍏':'green_apple','🍎':'red_apple','🍐':'pear','🍊':'mandarin','🍋':'lemon','🍌':'banana','🍉':'watermelon','🍇':'grapes','🍓':'strawberry','🍈':'melon','🍒':'cherries','🍑':'peach','🍍':'pineapple','🥥':'coconut','🥝':'kiwi','🍅':'tomato','🥑':'avocado','🍆':'eggplant','🥔':'potato','🥕':'carrot','🌽':'corn','🌶️':'hot_pepper','🥒':'cucumber','🥬':'leafy_green','🥦':'broccoli','🥜':'peanuts','🍞':'bread','🥐':'croissant','🥖':'baguette','🥨':'pretzel','🥯':'bagel','🥞':'pancakes','🧀':'cheese','🍖':'meat_bone','🍗':'poultry_leg','🥩':'steak','🥓':'bacon','🍔':'burger','🍟':'fries','🍕':'pizza','🌭':'hot_dog','🥪':'sandwich','🌮':'taco','🌯':'burrito','🥙':'flatbread','🥚':'egg','🍳':'cooking','🥘':'shallow_pan','🍲':'pot_food','🥣':'bowl_spoon','🥗':'salad','🍿':'popcorn','🧂':'salt','🥫':'canned_food','🍱':'bento','🍘':'rice_cracker','🍙':'rice_ball','🍚':'rice','🍛':'curry_rice','🍜':'noodles','🍝':'spaghetti','🍠':'sweet_potato','🍢':'oden','🍣':'sushi','🍤':'fried_shrimp','🍥':'fish_cake','🥮':'moon_cake','🍡':'dango','🥟':'dumpling','🥠':'fortune_cookie','🥡':'takeout_box','🍦':'soft_icecream','🍧':'shaved_ice','🍨':'icecream','🍩':'donut','🍪':'cookie','🎂':'birthday_cake','🍰':'cake','🧁':'cupcake','🥧':'pie','🍫':'chocolate','🍬':'candy','🍭':'lollipop','🍮':'custard','🍯':'honey','☕':'coffee','🍵':'tea','🥤':'cup_straw','🍶':'sake','🍾':'champagne','🍷':'wine_glass','🍸':'cocktail','🍹':'tropical_drink','🍺':'beer','🍻':'beers','🥂':'clink_glasses','🥃':'glass_whiskey',
    
    // ARTS & CRAFTS
    '🎨':'palette','🖌️':'paintbrush','🖍️':'marker','📝':'memo','✏️':'pencil','✒️':'black_nib','🖊️':'pen','🖋️':'fountain_pen','📎':'paperclip','🖇️':'linked_paperclips','✂️':'scissors','📏':'ruler','📐':'triangle_ruler','📕':'book_red','📗':'book_green','📘':'book_blue','📙':'book_orange','📚':'books','📖':'open_book','📜':'scroll','📄':'page','📰':'newspaper','📃':'page_curl','📑':'bookmark_tabs','🔖':'bookmark','📛':'name_badge','🏷️':'label','💮':'white_flower','🖼️':'framed_picture','🖥️':'desktop','🖨️':'printer','🖱️':'mouse','🖲️':'trackball','💾':'floppy_disk','💿':'cd','📀':'dvd','📼':'videocassette','📷':'camera','📸':'camera_flash','📹':'video_camera','📺':'tv','📻':'radio','🎙️':'studio_microphone','🎚️':'level_slider','🎛️':'knobs','🎼':'music_score','🎵':'note','🎶':'notes','🎤':'microphone','🎧':'headphone','🎷':'saxophone','🎸':'guitar','🎺':'trumpet','🎻':'violin','🥁':'drum','🪕':'banjo','🎬':'clapper','🎭':'performing_arts','🎪':'circus','🤹':'juggling','🎯':'dart','🎮':'video_game','🕹️':'joystick','🎲':'dice','♟️':'chess_pawn','🧩':'puzzle','🧸':'teddy_bear',
    
    // TRAVEL
    '🗺️':'world_map','🗾':'map_japan','🏔️':'snow_mountain','⛰️':'mountain','🌋':'volcano','🌄':'sunrise_mountains','🌅':'sunrise','🌇':'sunset_buildings','🌉':'bridge_night','🏠':'house','🏡':'house_garden','🏢':'office','🏣':'jp_post','🏤':'post_office','🏥':'hospital','🏦':'bank','🏨':'hotel','🏩':'love_hotel','🏪':'store','🏫':'school','🏬':'department_store','🏭':'factory','🏯':'jp_castle','🏰':'castle','💒':'wedding','🗼':'tokyo_tower','🗽':'statue_liberty','⛪':'church','🕌':'mosque','🛕':'hindu_temple','🕍':'synagogue','⛲':'fountain','⛺':'tent','🌁':'foggy','🌃':'night_stars','🏙️':'cityscape','🌆':'dusk_city','🏗️':'construction','🧱':'brick','🛣️':'motorway','🛤️':'railway_track','🛖':'hut','🏝️':'desert_island','🏜️':'desert','🏖️':'beach_umbrella','🏕️':'camping','🚗':'car','🚕':'taxi','🚙':'suv','🚌':'bus','🚎':'trolley','🚑':'ambulance','🚒':'fire_engine','🚓':'police_car','🚐':'van','🚚':'truck','🚛':'articulated_truck','🚜':'tractor','🏎️':'race_car','🚨':'lights','🚲':'bike','🛴':'scooter','🛹':'skateboard','🛵':'scooter_motor','🚀':'rocket','🛸':'saucer','🚁':'helicopter','🛶':'canoe','⛵':'sailboat','🚢':'ship','⚓':'anchor','✈️':'plane','💺':'seat','🛰️':'satellite',
    
    // ACTIVITIES
    '⚽':'soccer','🏀':'basketball','🏈':'american_football','⚾':'baseball','🥎':'softball','🎾':'tennis','🏐':'volleyball','🏉':'rugby','🎱':'pool_8','🪀':'yo_yo','🏓':'pingpong','🏸':'badminton','🏒':'hockey','🏑':'field_hockey','🥍':'lacrosse','🏏':'cricket','🥅':'goal','⛳':'flag_hole','🪁':'kite','🏹':'bow','🎣':'fishing','🤿':'diving','🎽':'running_shirt','🎿':'ski','🛷':'sled','⛸️':'skate','🥌':'curling','🎯':'direct_hit','🎮':'game','🕹️':'joystick','🎲':'die','♟️':'pawn','🧩':'puzzle','🧸':'toy','🎨':'art','🎭':'theater','🎪':'big_top','🤹':'juggle','🎬':'clapper','🎤':'mic','🎧':'headset','🎼':'score','🎵':'note','🎶':'notes','🎙️':'studio_mic','🎚️':'slider','🎛️':'controls','🎹':'keyboard','🎷':'sax','🎸':'guitar','🎺':'trumpet','🎻':'violin','🥁':'drum','🪕':'banjo',
    
    // SYMBOLS
    '❤️':'red_heart','🧡':'orange_heart','💛':'yellow_heart','💚':'green_heart','💙':'blue_heart','💜':'purple_heart','🤎':'brown_heart','🖤':'black_heart','🤍':'white_heart','💔':'broken_heart','❣️':'exclamation_heart','💕':'two_hearts','💞':'revolving_hearts','💓':'beating_heart','💗':'growing_heart','💖':'sparkling_heart','💘':'arrow_heart','💝':'ribbon_heart','💟':'decoration','☮️':'peace','✝️':'cross','☪️':'star_crescent','🕉️':'om','☸️':'wheel','✡️':'star_david','🔯':'six_pointed','🕎':'menorah','☯️':'yin_yang','☦️':'orthodox','🛐':'worship','⚛️':'atom','🕸️':'web','♻️':'recycle','🔱':'trident','⚜️':'fleur_de_lis','🔰':'start','♈':'aries','♉':'taurus','♊':'gemini','♋':'cancer','♌':'leo','♍':'virgo','♎':'libra','♏':'scorpio','♐':'sagittarius','♑':'capricorn','♒':'aquarius','♓':'pisces','✅':'check','☑️':'box_check','✔️':'heavy_check','❌':'x','❎':'x_button','➕':'plus','➖':'minus','➗':'divide','✖️':'multiply','🔢':'numbers','🔠':'abc_upper','🔡':'abc_lower','🔣':'symbols','🔤':'letters','🅰️':'a','🆎':'ab','🅱️':'b','🆑':'cl','🆒':'cool','🆓':'free','ℹ️':'info','🆔':'id','⛎':'ophiuchus','🆕':'new','🆖':'ng','🅾️':'o','🆗':'ok','🅿️':'p','🆘':'sos','🆙':'up','🆚':'vs','🈁':'here','🈂️':'sa','🈷️':'month','🈶':'charged','🈯️':'reserved','🉐':'bargain','🈹':'discount','🈚️':'no_charge','🈲':'prohibited','🉑':'acceptable','🈸':'apply','🈴':'pass','🈳':'vacancy','㊗️':'congrats','㊙️':'secret','🈺':'open','🈵':'full','🔴':'circle_red','🟠':'circle_orange','🟡':'circle_yellow','🟢':'circle_green','🔵':'circle_blue','🟣':'circle_purple','🟤':'circle_brown','⚫':'circle_black','⚪':'circle_white','🟥':'square_red','🟧':'square_orange','🟨':'square_yellow','🟩':'square_green','🟦':'square_blue','🟪':'square_purple','🟫':'square_brown','⬛':'large_black','⬜':'large_white','◼️':'medium_black','◻️':'medium_white','◾':'med_small_black','◽':'med_small_white','▪️':'small_black','▫️':'small_white','🔶':'diamond_orange','🔷':'diamond_blue','🔸':'small_diamond_orange','🔹':'small_diamond_blue','🔺':'triangle_red_up','🔻':'triangle_red_down','💠':'diamond_dot','🔳':'button_white','🔲':'button_black','🏁':'checkered_flag','🚩':'triangular_flag','🎌':'crossed_flags','🏴':'black_flag','🏳️':'white_flag','🏳️‍🌈':'rainbow_flag','🏴‍☠️':'pirate_flag','🇬🇷':'greece','🇮🇹':'italy','🇺🇸':'usa','🇪🇺':'eu','🇫🇷':'france','🇩🇪':'germany','🇪🇸':'spain','🇨🇳':'china','🇯🇵':'japan','🇰🇷':'korea','🇧🇷':'brazil'
});

// Full Categories List
window.EMOJI_CATEGORIES = [
    { title: '😊 Smiles & Emotion', emojis: ['😀','😃','😄','😁','😅','😂','🤣','🙂','🙃','😉','😊','😇','🥰','😍','🤩','😘','😗','☺️','😚','😙','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤫','🤔','🤐','🤨','😐','😑','😶','😏','😒','🙄','😬','🤥','😌','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🤧','🥵','🥶','🥴','😵','🤯','🤠','🥳','🥸','😎','🤓','🧐','😕','😟','🙁','☹️','😮','😯','😲','😳','🥺','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖'] },
    { title: '👨 People & Body', emojis: ['👶','👧','🧒','👦','👩','🧑','👨','👴','👵','🧓','👱','👨‍⚕️','👩‍⚕️','👨‍🎓','👩‍🎓','👨‍🏫','👩‍🏫','👨‍⚖️','👩‍⚖️','👨‍🌾','👩‍🌾','👨‍🍳','👩‍🍳','👨‍🔧','👩‍🔧','👨‍🏭','👩‍🏭','👨‍💼','👩‍💼','👨‍🔬','👩‍🔬','👨‍💻','👩‍💻','👨‍🎤','👩‍🎤','👨‍🎨','👩‍🎨','👨‍✈️','👩‍✈️','👨‍🚀','👩‍🚀','👨‍🚒','👩‍🚒','👮','🕵️','💂','👷','🤴','👸','👳','👲','🧕','🤵','👰','🤰','🤱','👼','🎅','🤶','🦸','🦹','🧙','🧚','🧛','🧜','🧝','🧞','🧟','💆','💇','🚶','🏃','💃','🕺','🕴️','🧖','🧗','🧘','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🧠','🦷','🦴','👀','👁️','👅','👄','🙌','👐','🤲','🤝','🙏','✍️'] },
    { title: '🐶 Animals', emojis: ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐷','🐮','🐸','🐵','🙈','🙉','🙊','🐒','🐔','🐧','🐦','🐤','🐣','🐥','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🐛','🦋','🐌','🐞','🐜','🦟','🦗','🕷️','🦂','🐢','🐍','🦎','🐙','🦑','🦐','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🐊','🐅','🐆','🦓','🦍','🦧','🐘','🦏','🦛','🐪','🐫','🦒','🦘','🐃','🐂','🐄','🐎','🐖','🐏','🐐','🐑','🦙','🦝','🦡','🦦','🦨','🐿️','🦔','🔥','💧','🌊','🎃','✨','🎋','🎍','🎀','🎁','🎈','🎉','🎊','🍼','🥛'] },
    { title: '🎨 Arts & Crafts', emojis: ['🎨','🖌️','🖍️','📝','✏️','✒️','🖊️','🖋️','📎','🖇️','✂️','📏','📐','📕','📗','📘','📙','📚','📖','📜','📄','📰','📃','📑','🔖','📛','🏷️','💮','🖼️','🖥️','🖨️','🖱️','🖲️','💾','💿','📀','📼','📷','📸','📹','📺','📻','🎙️','🎚️','🎛️','🎼','🎵','🎶','🎤','🎧','🎷','🎸','🎺','🎻','🥁','🪕','🎬','🎭','🎪','🤹','🎯','🎮','🕹️','🎲','♟️','🧩','🧸'] },
    { title: '✈️ Travel', emojis: ['🗺️','🗾','🏔️','⛰️','🌋','🌄','🌅','🌇','🌉','🏠','🏡','🏢','🏣','🏤','🏥','🏦','🏨','🏩','🏪','🏫','🏬','🏭','🏯','🏰','💒','🗼','🗽','⛪','🕌','🛕','🕍','⛲','⛺','🌁','🌃','🏙️','🌆','🏗️','🧱','🛣️','🛤️','🛖','🌊','🏝️','🏜️','🏖️','🏕️','🚗','🚕','🚙','🚌','🚎','🚑','🚒','🚓','🚐','🚚','🚛','🚜','🏎️','🚨','🚲','🛴','🛹','🛵','🚀','🛸','🚁','🛶','⛵','🚢','⚓','✈️','💺','🛰️'] },
    { title: '⚽ Activities', emojis: ['⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🎱','🪀','🏓','🏸','🏒','🏑','🥍','🏏','🥅','⛳','🪁','🏹','🎣','🤿','🎽','🎿','🛷','⛸️','🥌','🎯','🎮','🕹️','🎲','♟️','🧩','🧸','🎭','🎪','🤹','🎬','🎤','🎧','🎼','🎵','🎶','🎙️','🎚️','🎛️','🎹','🎷','🎸','🎺','🎻','🥁','🪕'] },
    { title: '❤️ Symbols', emojis: ['❤️','🧡','💛','💚','💙','💜','🤎','🖤','🤍','💔','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🕉️','☸️','✡️','🔯','🕎','☯️','☦️','🛐','⚛️','🕸️','♻️','🔱','⚜️','🔰','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓','✅','☑️','✔️','❌','❎','➕','➖','➗','✖️','🔢','🔠','🔡','🔣','🔤','🅰️','🆎','🅱️','🆑','🆒','🆓','ℹ️','🆔','⛎','🆕','🆖','🅾️','🆗','🅿️','🆘','🆙','🆚','🈁','🈂️','🈷️','🈶','🈯️','🉐','🈹','🈚️','🈲','🉑','🈸','🈴','🈳','㊗️','㊙️','🈺','🈵','🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫','⚪','🟥','🟧','🟨','🟩','🟦','🟪','🟫','⬛','⬜','◼️','◻️','◾','◽','▪️','▫️','🔶','🔷','🔸','🔹','🔺','🔻','💠','🔳','🔲','🏁','🚩','🎌','🏴','🏳️','🏳️‍🌈','🏴‍☠️','🇬🇷','🇮🇹','🇺🇸','🇪🇺','🇫🇷','🇩🇪','🇪🇸','🇨🇳','🇯🇵','🇰🇷','🇧🇷'] }
];

// Helper function for converting emoji to word
window.emojiToWord = function(emoji) {
    return window.EMOJI_MAPPING[emoji] || 'emote';
};

console.log('✅ Emoji data loaded successfully - Categories:', window.EMOJI_CATEGORIES.length);
console.log('Total mappings:', Object.keys(window.EMOJI_MAPPING).length);