// --- COMPREHENSIVE ENGLISH EMOJI TO WORD MAPPING ---
// Fallback data - loads before app.js
const EMOJI_MAPPING = {
    // SMILEYS & EMOTION
    '😀': 'grinning', '😃': 'smile', '😄': 'happy', '😁': 'cheerful', '😅': 'nervous',
    '😂': 'joy', '🤣': 'laughing', '🙂': 'smile', '🙃': 'upside', '😉': 'wink',
    '😊': 'shy_smile', '😇': 'angel', '🥰': 'love', '😍': 'heart_eyes', '🤩': 'stars',
    '😘': 'kiss', '😗': 'kiss', '☺️': 'relaxed', '😚': 'kiss_closed', '😙': 'kiss_smile',
    '😋': 'yum', '😛': 'tongue', '😜': 'playful', '🤪': 'zany', '😝': 'silly',
    '🤑': 'money', '🤗': 'hug', '🤭': 'secret', '🤫': 'shush', '🤔': 'thinking',
    '🤐': 'silent', '🤨': 'suspicious', '😐': 'neutral', '😑': 'blank', '😶': 'mute',
    '😏': 'smirk', '😒': 'unamused', '🙄': 'eye_roll', '😬': 'grimace', '🤥': 'lie',
    '😌': 'relief', '😔': 'sad', '😪': 'sleepy', '🤤': 'drooling', '😴': 'sleeping',
    '😷': 'mask', '🤒': 'sick', '🤕': 'hurt', '🤢': 'nausea', '🤮': 'vomit',
    '🤧': 'sneeze', '🥵': 'hot', '🥶': 'cold', '🥴': 'woozy', '😵': 'dizzy',
    '🤯': 'exploding_head', '🤠': 'cowboy', '🥳': 'party', '🥸': 'disguised', '😎': 'cool',
    '🤓': 'nerd', '🧐': 'monocle', '😕': 'confused', '😟': 'worried', '🙁': 'frown',
    '☹️': 'sad', '😮': 'surprised', '😯': 'hushed', '😲': 'astonished', '😳': 'flushed',
    '🥺': 'pleading', '😦': 'open_mouth', '😧': 'anguish', '😨': 'fear', '😰': 'anxious',
    '😥': 'relief_sad', '😢': 'cry', '😭': 'sob', '😱': 'scream', '😖': 'struggle',
    '😣': 'persevere', '😞': 'disappointed', '😓': 'sweat', '😩': 'weary', '😫': 'tired',
    '🥱': 'yawn', '😤': 'triumph', '😡': 'angry', '😠': 'mad', '🤬': 'cursing',
    '😈': 'devil', '👿': 'imp', '💀': 'skull', '☠️': 'skull_bones', '💩': 'poop',
    '🤡': 'clown', '👹': 'ogre', '👺': 'goblin', '👻': 'ghost', '👽': 'alien',
    '👾': 'space_invader', '🤖': 'robot', '💨': 'dashing_away', '💤': 'zzz',

    // ANIMALS & NATURE
    '🐶': 'dog', '🐱': 'cat', '🐭': 'mouse', '🐹': 'hamster', '🐰': 'rabbit',
    '🦊': 'fox', '🐻': 'bear', '🐼': 'panda', '🐨': 'koala', '🐯': 'tiger',
    '🦁': 'lion', '🐮': 'cow', '🐷': 'pig', '🐸': 'frog', '🐵': 'monkey',
    '🙈': 'see_no_evil', '🙉': 'hear_no_evil', '🙊': 'speak_no_evil', '🐒': 'monkey',
    '🐔': 'chicken', '🐧': 'penguin', '🐦': 'bird', '🐤': 'baby_chick', '🐥': 'front_facing_chick',
    '🐣': 'hatching_chick', '🦆': 'duck', '🦅': 'eagle', '🦉': 'owl', '🦇': 'bat',
    '🐺': 'wolf', '🐗': 'boar', '🐴': 'horse', '🦄': 'unicorn', '🐝': 'bee',
    '🐛': 'bug', '🦋': 'butterfly', '🐌': 'snail', '🐞': 'lady_beetle', '🐜': 'ant',
    '🦟': 'mosquito', '🕷️': 'spider', '🦂': 'scorpion', '🐢': 'turtle', '🐍': 'snake',
    '🦎': 'lizard', '🐙': 'octopus', '🦑': 'squid', '🦐': 'shrimp', '🦀': 'crab',
    '🐡': 'blowfish', '🐠': 'tropical_fish', '🐟': 'fish', '🐬': 'dolphin', '🐳': 'whale',
    '🐋': 'whale', '🦈': 'shark', '🐊': 'crocodile', '🐅': 'tiger', '🐆': 'leopard',
    '🦓': 'zebra', '🦍': 'gorilla', '🐘': 'elephant', '🦏': 'rhino', '🦛': 'hippopotamus',
    '🐪': 'camel', '🐫': 'two_hump_camel', '🦒': 'giraffe', '🦘': 'kangaroo', '🐃': 'water_buffalo',
    '🐂': 'ox', '🐄': 'cow', '🐎': 'horse', '🐖': 'pig', '🐏': 'ram',
    '🐐': 'goat', '🐑': 'sheep', '🦙': 'llama', '🦝': 'raccoon', '🦡': 'badger',
    '🦦': 'otter', '🦨': 'skunk', '🐿️': 'chipmunk', '🦔': 'hedgehog', '🔥': 'fire',
    '💧': 'droplet', '🌊': 'water_wave', '🎄': 'christmas_tree', '🎃': 'jack_o_lantern',
    '✨': 'sparkles', '🎋': 'tanabata', '🎍': 'pine_decorations', '🎀': 'ribbon', '🎁': 'gift',
    '🎈': 'balloon', '🎉': 'party_popper', '🎊': 'confetti_ball', '🍼': 'baby_bottle', '🥛': 'glass_of_milk',

    // FOOD & DRINK
    '🍏': 'green_apple', '🍎': 'red_apple', '🍐': 'pear', '🍊': 'mandarin', '🍋': 'lemon',
    '🍌': 'banana', '🍉': 'watermelon', '🍇': 'grapes', '🍓': 'strawberry', '🍈': 'melon',
    '🍒': 'cherries', '🍑': 'peach', '🍍': 'pineapple', '🥥': 'coconut', '🥝': 'kiwi_fruit',
    '🍅': 'tomato', '🥑': 'avocado', '🍆': 'eggplant', '🥔': 'potato', '🥕': 'carrot',
    '🌽': 'ear_of_corn', '🌶️': 'hot_pepper', '🥒': 'cucumber', '🥬': 'leafy_greens', '🥦': 'broccoli',
    '🍄': 'mushroom', '🥜': 'peanuts', '🌰': 'chestnut', '🍞': 'bread', '🥐': 'croissant',
    '🥖': 'baguette', '🥨': 'pretzel', '🥯': 'bagel', '🥞': 'pancakes', '🧀': 'cheese',
    '🍖': 'meat_on_bone', '🍗': 'poultry_leg', '🥩': 'steak', '🥓': 'bacon', '🍔': 'burger',
    '🍟': 'french_fries', '🍕': 'pizza', '🌭': 'hot_dog', '🥪': 'sandwich', '🌮': 'taco',
    '🌯': 'burrito', '🥙': 'stuffed_flatbread', '🥚': 'egg', '🍳': 'cooking', '🥘': 'shallow_pan_of_food',
    '🍲': 'pot_of_food', '🥣': 'bowl_with_spoon', '🥗': 'green_salad', '🍿': 'popcorn', '🧂': 'salt',
    '🥫': 'canned_food', '🍱': 'bento_box', '🍘': 'rice_cracker', '🍙': 'rice_ball', '🍚': 'cooked_rice',
    '🍛': 'curry_rice', '🍜': 'steaming_bowl', '🍝': 'spaghetti', '🍠': 'roasted_sweet_potato', '🍢': 'oden',
    '🍣': 'sushi', '🍤': 'fried_shrimp', '🍥': 'fish_cake_with_swirl', '🥮': 'moon_cake', '🍡': 'dango',
    '🥟': 'dumpling', '🥠': 'fortune_cookie', '🥡': 'takeout_container', '🍦': 'soft_ice_cream', '🍧': 'shaved_ice',
    '🍨': 'ice_cream', '🍩': 'donut', '🍪': 'cookie', '🎂': 'birthday_cake', '🍰': 'shortcake',
    '🧁': 'cupcake', '🥧': 'pie', '🍫': 'chocolate_bar', '🍬': 'candy', '🍭': 'lollipop',
    '🍮': 'custard', '🍯': 'honey_pot', '☕': 'hot_beverage', '🍵': 'teacup_without_handle', '🥤': 'cup_with_straw',
    '🍶': 'sake', '🍾': 'bottle_with_popping_cork', '🍷': 'wine_glass', '🍸': 'cocktail_glass', '🍹': 'tropical_drink',
    '🍺': 'beer_mug', '🍻': 'clinking_beer_mugs', '🥂': 'clinking_glasses', '🥃': 'tumbler_glass', '🥛': 'glass_of_milk',

    // ACTIVITIES & SPORTS
    '⚽': 'soccer_ball', '🏀': 'basketball', '🏈': 'american_football', '⚾': 'baseball', '🥎': 'softball',
    '🎾': 'tennis', '🏐': 'volleyball', '🏉': 'rugby_football', '🎱': 'pool_8_ball', '🪀': 'yo_yo',
    '🏓': 'ping_pong', '🏸': 'badminton', '🏒': 'ice_hockey', '🏑': 'field_hockey', '🥍': 'lacrosse',
    '🏏': 'cricket_game', '🥅': 'goal_net', '⛳': 'flag_in_hole', '🪁': 'kite', '🏹': 'bow_and_arrow',
    '🎣': 'fishing_pole', '🤿': 'diving_mask', '🎽': 'running_shirt', '🎿': 'skis', '🛷': 'sled',
    '⛸️': 'ice_skate', '🥌': 'curling_stone', '🎯': 'direct_hit', '🎮': 'video_game', '🕹️': 'joystick',
    '🎲': 'game_die', '♟️': 'chess_pawn', '🧩': 'puzzle_piece', '🧸': 'teddy_bear', '🎨': 'artist_palette',
    '🎭': 'performing_arts', '🎪': 'circus_tent', '🤹': 'juggling', '🎬': 'clapper_board', '🎤': 'microphone',
    '🎧': 'headphone', '🎼': 'musical_score', '🎵': 'musical_note', '🎶': 'musical_notes', '🎙️': 'studio_microphone',
    '🎚️': 'level_slider', '🎛️': 'control_knobs', '🎹': 'musical_keyboard', '🎷': 'saxophone', '🎸': 'guitar',
    '🎺': 'trumpet', '🎻': 'violin', '🥁': 'drum', '🪕': 'banjo', '🎷': 'saxophone',

    // TRAVEL & PLACES
    '🚗': 'automobile', '🚕': 'taxi', '🚙': 'sport_utility_vehicle', '🚌': 'bus', '🚎': 'trolleybus',
    '🚑': 'ambulance', '🚒': 'fire_engine', '🚓': 'police_car', '🚐': 'minibus', '🚚': 'delivery_truck',
    '🚛': 'articulated_lorry', '🚜': 'tractor', '🏎️': 'race_car', '🚨': 'police_car_light', '🚲': 'bicycle',
    '🛴': 'kick_scooter', '🛹': 'skateboard', '🛵': 'motor_scooter', '🚀': 'rocket', '🛸': 'flying_saucer',
    '🚁': 'helicopter', '🛶': 'canoe', '⛵': 'sailboat', '🚢': 'ship', '✈️': 'airplane',
    '💺': 'seat', '🛰️': 'satellite', '🏠': 'house', '🏡': 'house_with_garden', '🏢': 'office_building',
    '🏣': 'japanese_post_office', '🏤': 'post_office', '🏥': 'hospital', '🏦': 'bank', '🏨': 'hotel',
    '🏩': 'love_hotel', '🏪': 'convenience_store', '🏫': 'school', '🏬': 'department_store', '🏭': 'factory',
    '🏯': 'japanese_castle', '🏰': 'castle', '💒': 'wedding', '🗼': 'tokyo_tower', '🗽': 'statue_of_liberty',
    '⛪': 'church', '🕌': 'mosque', '🛕': 'hindu_temple', '🕍': 'synagogue', '⛲': 'fountain',
    '⛺': 'tent', '🌁': 'foggy', '🌃': 'night_with_stars', '🏙️': 'cityscape', '🌇': 'sunset_over_buildings',
    '🌆': 'cityscape_at_dusk', '🏗️': 'building_construction', '🗿': 'moai', '🛤️': 'railway_track', '🛣️': 'motorway',
    '🗺️': 'world_map', '🗾': 'map_of_japan', '🏔️': 'snow_capped_mountain', '⛰️': 'mountain', '🌋': 'volcano',
    '🌄': 'sunrise_over_mountains', '🌅': 'sunrise', '🌌': 'milky_way', '🌉': 'bridge_at_night', '🏝️': 'desert_island',
    '🏜️': 'desert', '🏖️': 'beach_with_umbrella', '🌊': 'water_wave', '🎑': 'moon_viewing_ceremony', '🌇': 'sunset',

    // OBJECTS
    '⌚': 'watch', '📱': 'mobile_phone', '📲': 'mobile_with_arrow', '💻': 'laptop', '🖥️': 'desktop_computer',
    '🖨️': 'printer', '⌨️': 'keyboard', '🖱️': 'computer_mouse', '🖲️': 'trackball', '💾': 'floppy_disk',
    '💿': 'optical_disc', '📀': 'dvd', '📼': 'videocassette', '📷': 'camera', '📸': 'camera_with_flash',
    '📹': 'video_camera', '📺': 'television', '📻': 'radio', '🎙️': 'studio_microphone', '🎚️': 'level_slider',
    '🎛️': 'control_knobs', '📞': 'telephone_receiver', '📟': 'pager', '📠': 'fax_machine', '🔋': 'battery',
    '🔌': 'electric_plug', '💡': 'light_bulb', '🔦': 'flashlight', '🕯️': 'candle', '🗑️': 'wastebasket',
    '🪓': 'axe', '🔪': 'kitchen_knife', '🏺': 'amphora', '🔍': 'magnifying_glass_tilted_left', '🔎': 'magnifying_glass_tilted_right',
    '🕳️': 'hole', '💣': 'bomb', '🔫': 'pistol', '🪃': 'boomerang', '🏹': 'bow_and_arrow',
    '🛡️': 'shield', '🔧': 'wrench', '🔨': 'hammer', '⛏️': 'pick', '🔩': 'bolt',
    '⚙️': 'gear', '🗜️': 'clamp', '⚖️': 'balance_scale', '🔗': 'link', '⛓️': 'chains',
    '🧰': 'toolbox', '🧲': 'magnet', '🧪': 'test_tube', '🧫': 'petri_dish', '🧬': 'dna',
    '🔬': 'microscope', '🔭': 'telescope', '📡': 'satellite_antenna', '💉': 'syringe', '💊': 'pill',
    '🩹': 'adhesive_bandage', '🩺': 'stethoscope', '🚪': 'door', '🛏️': 'bed', '🛋️': 'couch_and_lamp',
    '🚽': 'toilet', '🚿': 'shower', '🛁': 'bathtub', '🪑': 'chair', '🚰': 'potable_water',
    '🛒': 'shopping_cart', '🚬': 'cigarette', '⚰️': 'coffin', '⚱️': 'funeral_urn', '🗿': 'moai',
    '🏧': 'atm_sign', '🚮': 'put_litter_in_its_place', '🕳️': 'manhole', '💎': 'gem_stone', '🔐': 'locked_with_key',
    '🔒': 'locked', '🔓': 'unlocked', '🔏': 'locked_with_pen', '🔑': 'key', '🗝️': 'old_key',
    '🔨': 'hammer', '🪓': 'axe', '🪚': 'carpentry_saw', '🔧': 'wrench', '🔩': 'screw',
    '⚙️': 'gear', '🗜️': 'clamp', '⚖️': 'balance_scale', '🪝': 'hook', '🔗': 'link',
    '⛓️': 'chains', '🧰': 'toolbox', '🧲': 'magnet', '🧪': 'test_tube', '🧫': 'petri_dish',
    '🧬': 'dna', '🔬': 'microscope', '🔭': 'telescope', '📡': 'satellite', '💉': 'syringe',
    
    // SYMBOLS
    '❤️': 'red_heart', '🧡': 'orange_heart', '💛': 'yellow_heart', '💚': 'green_heart', '💙': 'blue_heart',
    '💜': 'purple_heart', '🤎': 'brown_heart', '🖤': 'black_heart', '🤍': 'white_heart', '💔': 'broken_heart',
    '❣️': 'heart_exclamation', '💕': 'two_hearts', '💞': 'revolving_hearts', '💓': 'beating_heart', '💗': 'growing_heart',
    '💖': 'sparkling_heart', '💘': 'heart_with_arrow', '💝': 'heart_with_ribbon', '💟': 'heart_decoration', '☮️': 'peace_symbol',
    '✝️': 'latin_cross', '☪️': 'star_and_crescent', '🕉️': 'om', '☸️': 'wheel_of_dharma', '✡️': 'star_of_david',
    '🔯': 'six_pointed_star', '🕎': 'menorah', '☯️': 'yin_yang', '☦️': 'orthodox_cross', '🛐': 'place_of_worship',
    '⚛️': 'atom_symbol', '🕸️': 'spider_web', '♻️': 'recycling_symbol', '🔱': 'trident_emblem', '⚜️': 'fleur_de_lis',
    '🔰': 'japanese_symbol_for_beginner', '♈': 'aries', '♉': 'taurus', '♊': 'gemini', '♋': 'cancer',
    '♌': 'leo', '♍': 'virgo', '♎': 'libra', '♏': 'scorpio', '♐': 'sagittarius',
    '♑': 'capricorn', '♒': 'aquarius', '♓': 'pisces', '🆔': 'id_button', '⚧️': 'transgender_symbol',
    '🔠': 'input_latin_uppercase', '🔡': 'input_latin_lowercase', '🔢': 'input_numbers', '🔣': 'input_symbols', '🔤': 'input_latin_letters',
    '🅰️': 'a_button', '🆎': 'ab_button', '🅱️': 'b_button', '🆑': 'cl_button', '🆒': 'cool_button',
    '🆓': 'free_button', 'ℹ️': 'information', '🆔': 'id_button', '⛎': 'ophiuchus', '🆕': 'new_button',
    '🆖': 'ng_button', '🅾️': 'o_button', '🆗': 'ok_button', '🅿️': 'p_button', '🆘': 'sos_button',
    '🆙': 'up_button', '🆚': 'vs_button', '🈁': 'here_button', '🈂️': 'sa_button', '🈷️': 'month_button',
    '🈶': 'not_free_button', '🈯️': 'reserved_button', '🉐': 'bargain_button', '🈹': 'discount_button', '🈚️': 'free_button',
    '🈲': 'prohibited_button', '🉑': 'acceptable_button', '🈸': 'application_button', '🈴': 'passing_grade_button', '🈳': 'vacancy_button',
    '㊗️': 'congratulations_button', '㊙️': 'secret_button', '🈺': 'open_for_business_button', '🈵': 'no_vacancy_button', '🔴': 'red_circle',
    '🟠': 'orange_circle', '🟡': 'yellow_circle', '🟢': 'green_circle', '🔵': 'blue_circle', '🟣': 'purple_circle',
    '🟤': 'brown_circle', '⚫': 'black_circle', '⚪': 'white_circle', '🟥': 'red_square', '🟧': 'orange_square',
    '🟨': 'yellow_square', '🟩': 'green_square', '🟦': 'blue_square', '🟪': 'purple_square', '🟫': 'brown_square',
    '⬛': 'black_large_square', '⬜': 'white_large_square', '◼️': 'black_medium_square', '◻️': 'white_medium_square',
    '◾': 'black_medium_small_square', '◽': 'white_medium_small_square', '▪️': 'black_small_square', '▫️': 'white_small_square',
    '🔶': 'large_orange_diamond', '🔷': 'large_blue_diamond', '🔸': 'small_orange_diamond', '🔹': 'small_blue_diamond',
    '🔺': 'red_triangle_pointed_up', '🔻': 'red_triangle_pointed_down', '💠': 'diamond_with_dot', '🔳': 'white_square_button', '🔲': 'black_square_button'
};

// --- EMOJI DATA FOR DROPDOWN CATEGORIES ---
const EMOJI_CATEGORIES = [
    { title: '😊 Smiles & Emotion', emojis: ['😀','😃','😄','😁','😅','😂','🤣','🙂','🙃','😉','😊','😇','🥰','😍','🤩','😘','😗','☺️','😚','😙','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤫','🤔','🤐','🤨','😐','😑','😶','😏','😒','🙄','😬','🤥','😌','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🤧','🥵','🥶','🥴','😵','🤯','🤠','🥳','🥸','😎','🤓','🧐','😕','😟','🙁','☹️','😮','😯','😲','😳','🥺','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖'] },
    { title: '👨 People & Body', emojis: ['👶','👧','🧒','👦','👩','🧑','👨','👴','👵','🧓','👱','👨‍⚕️','👩‍⚕️','👨‍🎓','👩‍🎓','👨‍🏫','👩‍🏫','👨‍⚖️','👩‍⚖️','👨‍🌾','👩‍🌾','👨‍🍳','👩‍🍳','👨‍🔧','👩‍🔧','👨‍🏭','👩‍🏭','👨‍💼','👩‍💼','👨‍🔬','👩‍🔬','👨‍💻','👩‍💻','👨‍🎤','👩‍🎤','👨‍🎨','👩‍🎨','👨‍✈️','👩‍✈️','👨‍🚀','👩‍🚀','👨‍🚒','👩‍🚒','👮','🕵️','💂','👷','🤴','👸','👳','👲','🧕','🤵','👰','🤰','🤱','👼','🎅','🤶','🦸','🦹','🧙','🧚','🧛','🧜','🧝','🧞','🧟','💆','💇','🚶','🏃','💃','🕺','🕴️','🧖','🧗','🧘','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🧠','🦷','🦴','👀','👁️','👅','👄'] },
    { title: '🐶 Animals', emojis: ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐷','🐮','🐸','🐵','🙈','🙉','🙊','🐒','🐔','🐧','🐦','🐤','🐣','🐥','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🐛','🦋','🐌','🐞','🐜','🦟','🦗','🕷️','🦂','🐢','🐍','🦎','🐙','🦑','🦐','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🐊','🐅','🐆','🦓','🦍','🦧','🐘','🦏','🦛','🐪','🐫','🦒','🦘','🐃','🐂','🐄','🐎','🐖','🐏','🐐','🐑','🦙','🦝','🦡','🦦','🦨','🐿️','🦔','🔥','💧','🌊','🎄','🎃','✨','🎋','🎍','🎀','🎁','🎈','🎉','🎊','🍼','🥛'] },
    { title: '⚽ Activities', emojis: ['⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🎱','🪀','🏓','🏸','🏒','🏑','🥍','🏏','🥅','⛳','🪁','🏹','🎣','🤿','🎽','🎿','🛷','⛸️','🥌','🎯','🎮','🕹️','🎲','♟️','🧩','🧸','🎨','🎭','🎪','🤹','🎬','🎤','🎧','🎼','🎵','🎶','🎙️','🎚️','🎛️','🎹','🎷','🎸','🎺','🎻','🥁','🪕'] },
    { title: '✈️ Travel', emojis: ['🗺️','🗾','🏔️','⛰️','🌋','🌄','🌅','🌇','🌉','🏠','🏡','🏢','🏣','🏤','🏥','🏦','🏨','🏩','🏪','🏫','🏬','🏭','🏯','🏰','💒','🗼','🗽','⛪','🕌','🛕','🕍','⛲','⛺','🌁','🌃','🏙️','🌆','🏗️','🧱','🛣️','🛤️','🛖','🌊','🏝️','🏜️','🏖️','🏕️','🚗','🚕','🚙','🚌','🚎','🚑','🚒','🚓','🚐','🚚','🚛','🚜','🏎️','🚨','🚲','🛴','🛹','🛵','🚀','🛸','🚁','🛶','⛵','🚢','⚓','✈️','💺','🛰️','🚁','🚟','🚠','🚡'] },
    { title: '❤️ Symbols', emojis: ['❤️','🧡','💛','💚','💙','💜','🤎','🖤','🤍','💔','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🕉️','☸️','✡️','🔯','🕎','☯️','☦️','🛐','⚛️','🕸️','♻️','🔱','⚜️','🔰','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓','🆔','⚧️','✅','☑️','✔️','❌','❎','➕','➖','➗','✖️','🔢','🔠','🔡','🔣','🔤','🅰️','🆎','🅱️','🆑','🆒','🆓','ℹ️','🆔','⛎','🆕','🆖','🅾️','🆗','🅿️','🆘','🆙','🆚','🈁','🈂️','🈷️','🈶','🈯️','🉐','🈹','🈚️','🈲','🉑','🈸','🈴','🈳','㊗️','㊙️','🈺','🈵','🔴','🟠','🟡','🟢','🔵','🟣','🟤','⚫','⚪','🟥','🟧','🟨','🟩','🟦','🟪','🟫','⬛','⬜','◼️','◻️','◾','◽','▪️','▫️','🔶','🔷','🔸','🔹','🔺','🔻','💠','🔳','🔲','🏁','🚩','🎌','🏴','🏳️','🏳️‍🌈','🇬🇷','🇮🇹','🇺🇸','🇪🇺','🇫🇷','🇩🇪','🇪🇸','🇨🇳','🇯🇵','🇰🇷','🇧🇷'] }
];

// Helper function to get word from emoji
function emojiToWord(emoji) {
    return EMOJI_MAPPING[emoji] || 'emote';
}